"""
Automated Intake Scanner & Course Plan Scaffolder
Scans the knowledge_dump/ drop zones, catalogs incoming teacher assets,
and generates a structured draft course plan.
"""

import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KNOWLEDGE_DIR = os.path.join(BASE_DIR, "knowledge_dump")

DROP_ZONES = [
    "raw_syllabi",
    "legacy_decks",
    "transcripts_and_notes",
    "reference_papers",
    "brainstorms"
]


def scan_drop_zones(base_dir=None):
    if base_dir is None:
        base_dir = BASE_DIR
    knowledge_dir = os.path.join(base_dir, "knowledge_dump")
    inventory = {}
    for zone in DROP_ZONES:
        zone_path = os.path.join(knowledge_dir, zone)
        if os.path.exists(zone_path):
            files = [f for f in os.listdir(zone_path) if not f.startswith(".")]
            inventory[zone] = files
        else:
            inventory[zone] = []
    return inventory


def generate_scaffolded_plan(inventory, output_path):
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Scaffolded Course Plan & Intake Inventory\n")
        f.write(f"**Generated by Intake Scanner:** {os.path.basename(output_path)}\n\n")
        f.write("## 1. Intake Drop Zone Inventory\n")
        for zone, files in inventory.items():
            f.write(f"### `{zone}/` ({len(files)} files)\n")
            if files:
                for f_name in files:
                    f.write(f"- `{f_name}`\n")
            else:
                f.write("- *No files currently staged in this drop zone.*\n")
            f.write("\n")

        f.write("## 2. Recommended Next Steps for the Educator\n")
        f.write("1. Review `engine/config.py` to customize your institution name, colors, and mascot.\n")
        f.write("2. Open `templates/competency_map_template.md` to map out your weekly competencies.\n")
        f.write("3. For each unit, generate guides from `templates/instructional_guide_template.md` and code labs from `templates/code_lab_template.py`.\n")
        f.write("4. Compile presentations using `engine/deck_generator.py`.\n")
        f.write("5. Run `engine/deck_auditor.py` to verify slide deck compliance before delivery.\n")
    return output_path


def scan_knowledge_dump():
    print("=" * 70)
    print("TEACHER COURSE FACTORY: KNOWLEDGE DUMP INTAKE SCANNER")
    print("=" * 70)

    if not os.path.exists(KNOWLEDGE_DIR):
        print(f"[FAIL] Knowledge dump directory not found at: {KNOWLEDGE_DIR}")
        return 1

    manifest_path = os.path.join(KNOWLEDGE_DIR, "course_intake_manifest.yaml")
    has_manifest = os.path.exists(manifest_path)
    print(f"Course Intake Manifest Detected: {'[PASS]' if has_manifest else '[WARN] (course_intake_manifest.yaml missing)'}")

    inventory = scan_drop_zones(BASE_DIR)
    total_files = sum(len(f) for f in inventory.values())
    for zone, files in inventory.items():
        print(f"  - {zone:<32}: {len(files):>2} files detected")

    print(f"\nTotal Intake Assets Inventoried: {total_files} files")

    scaffold_path = os.path.join(BASE_DIR, "scaffolded_course_plan.md")
    generate_scaffolded_plan(inventory, scaffold_path)
    print(f"\n[PASS] Scaffolded plan generated at: '{scaffold_path}'")
    print("=" * 70)
    return 0


if __name__ == "__main__":
    sys.exit(scan_knowledge_dump())

